pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/AmalgamatedCodersInc/IlluminateAI_Android_SDK")
            credentials {
                username = System.getenv("GPR_USER") ?: "" // For local publishing
                password = System.getenv("GPR_KEY") ?: ""  // For local publishing
            }
        }

    }
}

rootProject.name = "FindMyShade-Example"
include ':app'
